### ISSUE TITLE
The basic example throws a 405

### ISSUE THREAD

**Issue by GrantHoffman** [dapplo/Dapplo.Jira#48]
I'm using the basic example trying to find a task.  I'm getting a 405.
>'Response status code does not indicate success: 405 (Method Not Allowed).'

        public string JiraUrl = "https://id.atlassian.com/";
        public string Username = "";
        public string Password = "";

        public IJiraClient Initialize()
        {
            var jiraClient = JiraClient.Create(new Uri(JiraUrl));
            jiraClient.SetBasicAuthentication(Username, Password);
            return jiraClient;
        }

        public async Task FindTask(IJiraClient jiraClient)
        {
            var searchResult = await jiraClient.Issue.SearchAsync(Where.Text.Contains("VIV-2534"));
        }

**Comment by Lakritzator** [comment]
Hi, I had a huge stack of work to go through and finally got here...

It's hard to tell the issue here, with this little information, otherwise I would have answered right away.

I expect you are trying to login with wrong credentials, at Atlassian they changed their login system some time ago.
For me the username is my email account.

**Comment by Lakritzator** [comment]
Did you manage to have a look at this, or got any more information?

**Comment by Lakritzator** [comment]
Ping?

**Comment by Lakritzator** [comment]
Closing this, as I didn't hear from you and I have no idea what this could be.
Please ping me when you have time to follow up.
