### ISSUE TITLE
client.Issue.SearchAsync Expand on "names" Not Possible

### ISSUE THREAD

**Issue by willherr** [dapplo/Dapplo.Jira#50]
I don't see any way to retrieve the expanded names entity with result from `client.Issue.SearchAsync`. As you can see, [this](https://k15t.jira.com/rest/api/2/search?maxResults=1&expand=names) shows that the names are returned separate from the Issue entity, but there is no property to access them with the result from `client.Issue.SearchAsync`.

**Comment by Lakritzator** [comment]
Hi,

my library is by no means a perfect, all inclusive solution. Up to now I or users of this library didn't have a need for it yet.
I more or less didn't really know about it, although I do recall seeing it somewhere, seems a usefull addition.

I just added the property "FieldDisplayNames" to the search result, but you still will need to provide the "extend" either in the global configuration or when calling the search as I don't expect people to always use it.

Due to some bigger changes I still have some issues with tests failing, but a new version (1.1.x) should be available shortly.

Best wishes,
Robin

**Comment by willherr** [comment]
I definitely get that! I am still new to the Github community so I wasn't aware of a better way to express this desired functionality other than creating an Issue. I appreciate it!

**Comment by Lakritzator** [comment]
No problem, you did okay.
My CI/CD pipeline just build and tested 1.1.2, it's uploaded to nuget but might take upto 30 minutes before it is visible.
Let me know if that works for you, don't forget you will need to configure or supply the extends.

An example, different expand though, is here: https://github.com/dapplo/Dapplo.Jira/blob/master/src/Dapplo.Jira.Tests/IssueTests.cs#L265

**Comment by willherr** [comment]
I will give it a shot tomorrow! Thanks again. 

One thing to think about though, as you said your library is not an all inclusive solution. Would it provide clarity if for example the extends were passed to the search method via an enum list that is actually supported by the library rather than allowing "any" strings? Just food for thought.

`expand: new [] { Expand.Names } `

**Comment by Lakritzator** [comment]
With not providing an all inclusive solution, I mainly wanted to point out that there are areas (like the field names) which are missing.

I only add things which I need or sometimes what people request, especially as I provide this without cost I didn't plan on covering the whole atlassian jira data model and services. Of course I'm more than happy to accept PR's.

I think having an enumeration might help, but it only makes sense when all the expands are fixed.
This is a bit of a specific use-case, which we can also enable by extending the JqlIssueSearch class with a property when this can be enabled... which in fact than takes care of adding the "names" to the extend list.

There are many ways to improve the usage... but let's first see if my change works for you, I'm currently swamped with work (not just private things) and due to a weird issue it took me more time to add this simple functionality than I wanted. So I didn't manage to add a test for it, and I'm not 100% sure it works....

Background: Somehow Atlassian recently updated their API and now returns something different as Sprint information... this threw an exception on a completely different location than I was working on, which limited my time to invest.

**Comment by Lakritzator** [comment]
Does this mean it worked?

**Comment by willherr** [comment]
Yes it did, sorry I wasn't clear 🙂
