### ISSUE TITLE
Get Issue with Comments (renderedFields)

### ISSUE THREAD

**Issue by toertchn** [dapplo/Dapplo.Jira#60]
Don't have time to take a deeper look. When I try to get an issue with comments and also need the rendered Fields I get a JSON Exception:

`Newtonsoft.Json.JsonReaderException : Could not convert string to DateTimeOffset: 14/Dez/20 11:17 AM. Path 'renderedFields.comment.comments[0].created', line 1, position 38695.`

I think there is a RenderedComment class missing.

**Comment by Lakritzator** [comment]
Thanks for reporting this, due to a coincidence the locale I tested with matched with the JIRA server and allowed the values to be parsed. I change the locale to test with, and added RenderedComments / RenderedComment to fix the issue.

Due to a degradation with Azure Devops (some issues in Europe) I expect it takes a bit longer before the new version is available on nuget.org. But the version with this fix should be 1.1.35

**Comment by Lakritzator** [comment]
I just got informed it was published, might take a few minutes before you see it.
https://www.nuget.org/packages/Dapplo.Jira/1.1.35
